.TH LATEX209 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
latex209 \- structured text formatting and typesetting
.SH SYNOPSIS
.B latex209
.br
.SH DESCRIPTION
.BR latex209
is provided to process ancient LaTeX sources.  If you want to process
modern LaTeX sources, you should try
.BR latex
instead of this command.
.SH SEE ALSO
.BR latex (1)
.SH AUTHOR
This manual page was written by TSUCHIYA Masatoshi <tsuchiya@namazu.org>,
for the Debian GNU/Linux system (but may be used by others).
